// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20260616021125_staffnamess")]
    partial class staffnamess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.AssetSubItemHistory", b =>
                {
                    b.Property<int>("sub_item_history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sub_item_history_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("history_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("history_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int>("procurement_withdrawal_id")
                        .HasColumnType("int");

                    b.Property<int?>("staff_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("usage_type_id")
                        .HasColumnType("int");

                    b.HasKey("sub_item_history_id");

                    b.HasIndex("procurement_withdrawal_id");

                    b.HasIndex("staff_id");

                    b.HasIndex("usage_type_id");

                    b.ToTable("assetSubItemHistories");
                });

            modelBuilder.Entity("AssetCategory", b =>
                {
                    b.Property<int>("asset_category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("asset_category_id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("asset_category_id");

                    b.ToTable("assetCategories");
                });

            modelBuilder.Entity("AssetItem", b =>
                {
                    b.Property<int>("asset_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("asset_id"));

                    b.Property<int?>("acquisition_method_id")
                        .HasColumnType("int");

                    b.Property<string>("asset_code_prefix")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("asset_name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("department_id")
                        .HasColumnType("int");

                    b.Property<int?>("fund_category_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int?>("item_no")
                        .HasColumnType("int");

                    b.Property<int?>("procurement_record_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("receive_date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("asset_id");

                    b.HasIndex("acquisition_method_id");

                    b.HasIndex("department_id");

                    b.HasIndex("fund_category_id");

                    b.ToTable("assetItems");
                });

            modelBuilder.Entity("AssetSubItem", b =>
                {
                    b.Property<int>("asset_sub_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("asset_sub_item_id"));

                    b.Property<int>("asset_category_id")
                        .HasColumnType("int");

                    b.Property<int>("asset_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("fiscal_asset_year")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int?>("item_no")
                        .HasColumnType("int");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("running_end_no")
                        .HasColumnType("int");

                    b.Property<int>("running_start_no")
                        .HasColumnType("int");

                    b.Property<string>("sub_item_name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("total_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("unit_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("useful_life_year")
                        .HasColumnType("int");

                    b.HasKey("asset_sub_item_id");

                    b.HasIndex("asset_category_id");

                    b.HasIndex("asset_id");

                    b.HasIndex("unit_id");

                    b.ToTable("assetSubItems");
                });

            modelBuilder.Entity("Core.Entities.AcquisitionMethod", b =>
                {
                    b.Property<int>("acquisition_method_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("acquisition_method_id"));

                    b.Property<string>("acquisition_method_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("acquisition_method_id");

                    b.ToTable("acquisitionMethods");
                });

            modelBuilder.Entity("Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.AssetRepair", b =>
                {
                    b.Property<int>("asset_repair_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("asset_repair_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("decree_document_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("problem_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("procurement_withdrawal_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("repair_cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("repair_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("repair_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("repair_document_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("repair_shop_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("staff_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("asset_repair_id");

                    b.HasIndex("procurement_withdrawal_id");

                    b.HasIndex("staff_id");

                    b.ToTable("assetRepairs");
                });

            modelBuilder.Entity("Core.Entities.AssetUsageType", b =>
                {
                    b.Property<int>("usage_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usage_type_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("usage_type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usage_type_id");

                    b.ToTable("assetUsageTypes");
                });

            modelBuilder.Entity("Core.Entities.AssetWithdrawal", b =>
                {
                    b.Property<int>("procurement_withdrawal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("procurement_withdrawal_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int>("procurement_record_id")
                        .HasColumnType("int");

                    b.Property<string>("purpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staff_id")
                        .HasColumnType("int");

                    b.Property<string>("storage_location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("withdrawal_date")
                        .HasColumnType("date");

                    b.Property<string>("withdrawal_document_no")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("procurement_withdrawal_id");

                    b.HasIndex("procurement_record_id");

                    b.HasIndex("staff_id");

                    b.ToTable("assetWithdrawals");
                });

            modelBuilder.Entity("Core.Entities.Budget_sources", b =>
                {
                    b.Property<int>("budget_source_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("budget_source_id"));

                    b.Property<string>("budget_source_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("budget_source_id");

                    b.ToTable("budget_sources");
                });

            modelBuilder.Entity("Core.Entities.Departments", b =>
                {
                    b.Property<int>("department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("department_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("department_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("department_id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Core.Entities.Expense_types", b =>
                {
                    b.Property<int>("expense_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("expense_type_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("expense_type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("expense_type_id");

                    b.ToTable("expense_types");
                });

            modelBuilder.Entity("Core.Entities.Fiscal_years", b =>
                {
                    b.Property<int>("fiscal_year_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fiscal_year_id"));

                    b.Property<DateTime?>("closed_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("fiscal_year")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_closed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("year_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fiscal_year_id");

                    b.ToTable("fiscal_years");
                });

            modelBuilder.Entity("Core.Entities.Fund_categories", b =>
                {
                    b.Property<int>("fund_category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fund_category_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("fund_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("fund_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("fund_category_id");

                    b.ToTable("fund_categories");
                });

            modelBuilder.Entity("Core.Entities.HireDetail", b =>
                {
                    b.Property<int>("hire_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hire_detail_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("hire_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int>("item_no")
                        .HasColumnType("int");

                    b.Property<string>("operation_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("procurement_record_id")
                        .HasColumnType("int");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("total_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("unit_id")
                        .HasColumnType("int");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("hire_detail_id");

                    b.HasIndex("procurement_record_id");

                    b.HasIndex("unit_id");

                    b.ToTable("hireDetails");
                });

            modelBuilder.Entity("Core.Entities.MaterialIssueDetail", b =>
                {
                    b.Property<int>("issue_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("issue_detail_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("issue_date")
                        .HasColumnType("date");

                    b.Property<int>("material_item_id")
                        .HasColumnType("int");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("staff_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("issue_detail_id");

                    b.HasIndex("material_item_id");

                    b.HasIndex("staff_id");

                    b.ToTable("materialIssueDetails");
                });

            modelBuilder.Entity("Core.Entities.MaterialItem", b =>
                {
                    b.Property<int>("material_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("material_item_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("current_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("material_code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("material_name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("min_stock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("opening_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("quantity_in")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("quantity_out")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("unit_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("material_item_id");

                    b.HasIndex("unit_id");

                    b.ToTable("materialItems");
                });

            modelBuilder.Entity("Core.Entities.MaterialReceiveDetail", b =>
                {
                    b.Property<int>("receive_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("receive_detail_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int>("item_no")
                        .HasColumnType("int");

                    b.Property<int>("material_item_id")
                        .HasColumnType("int");

                    b.Property<string>("operation_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("procurement_record_id")
                        .HasColumnType("int");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("receive_detail_id");

                    b.HasIndex("material_item_id");

                    b.HasIndex("procurement_record_id");

                    b.ToTable("materialReceiveDetails");
                });

            modelBuilder.Entity("Core.Entities.MaterialStockCard", b =>
                {
                    b.Property<int>("stock_card_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stock_card_id"));

                    b.Property<string>("StaffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("balance_qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int?>("issue_detail_id")
                        .HasColumnType("int");

                    b.Property<int>("material_item_id")
                        .HasColumnType("int");

                    b.Property<int?>("procurement_record_id")
                        .HasColumnType("int");

                    b.Property<decimal>("quantity_in")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("quantity_out")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("receive_detail_id")
                        .HasColumnType("int");

                    b.Property<string>("reference_document_no")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("transaction_date")
                        .HasColumnType("date");

                    b.Property<string>("transaction_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("stock_card_id");

                    b.HasIndex("issue_detail_id");

                    b.HasIndex("material_item_id");

                    b.HasIndex("receive_detail_id");

                    b.ToTable("materialStockCards");
                });

            modelBuilder.Entity("Core.Entities.MaterialWithdrawal", b =>
                {
                    b.Property<int>("material_withdrawal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("material_withdrawal_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("material_receive_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("procurement_record_id")
                        .HasColumnType("int");

                    b.Property<string>("receive_document_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staff_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("withdrawal_document_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("material_withdrawal_id");

                    b.HasIndex("procurement_record_id");

                    b.HasIndex("staff_id");

                    b.ToTable("materialWithdrawals");
                });

            modelBuilder.Entity("Core.Entities.Operation_types", b =>
                {
                    b.Property<int>("operation_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("operation_type_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("operation_type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("operation_type_id");

                    b.ToTable("operation_types");
                });

            modelBuilder.Entity("Core.Entities.Positions", b =>
                {
                    b.Property<int>("position_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("position_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("position_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("position_id");

                    b.ToTable("positions");
                });

            modelBuilder.Entity("Core.Entities.Prefixes", b =>
                {
                    b.Property<int>("prefix_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prefix_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("prefix_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prefix_short_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("prefix_id");

                    b.ToTable("prefixes");
                });

            modelBuilder.Entity("Core.Entities.Procurement_records", b =>
                {
                    b.Property<int>("procurement_record_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("procurement_record_id"));

                    b.Property<string>("amount_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("approval_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("attachment_file_path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("budget_source_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("document_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("document_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("expense_type_id")
                        .HasColumnType("int");

                    b.Property<int>("fiscal_year_id")
                        .HasColumnType("int");

                    b.Property<int>("fund_category_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("inspection_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int>("operation_type_id")
                        .HasColumnType("int");

                    b.Property<int>("project_id")
                        .HasColumnType("int");

                    b.Property<string>("reference_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("staff_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("vendor_id")
                        .HasColumnType("int");

                    b.HasKey("procurement_record_id");

                    b.HasIndex("budget_source_id");

                    b.HasIndex("department_id");

                    b.HasIndex("expense_type_id");

                    b.HasIndex("fiscal_year_id");

                    b.HasIndex("fund_category_id");

                    b.HasIndex("operation_type_id");

                    b.HasIndex("project_id");

                    b.HasIndex("staff_id");

                    b.HasIndex("vendor_id");

                    b.ToTable("procurement_records");
                });

            modelBuilder.Entity("Core.Entities.Projects", b =>
                {
                    b.Property<int>("project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("project_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fiscal_year_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<decimal>("project_budget_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("project_code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("project_name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("staff_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("project_id");

                    b.HasIndex("fiscal_year_id");

                    b.HasIndex("staff_id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("Core.Entities.Staffs", b =>
                {
                    b.Property<int>("staff_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("staff_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("position_id")
                        .HasColumnType("int");

                    b.Property<int>("prefix_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("staff_id");

                    b.HasIndex("department_id");

                    b.HasIndex("position_id");

                    b.HasIndex("prefix_id");

                    b.ToTable("staffs");
                });

            modelBuilder.Entity("Core.Entities.Vendors", b =>
                {
                    b.Property<int>("vendor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vendor_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tax_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("vendor_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("vendor_id");

                    b.ToTable("vendors");
                });

            modelBuilder.Entity("MaterialUnit", b =>
                {
                    b.Property<int>("unit_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("unit_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("unit_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("unit_id");

                    b.ToTable("units");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-id",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "customer-id",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Entities.AssetSubItemHistory", b =>
                {
                    b.HasOne("Core.Entities.AssetWithdrawal", "AssetWithdrawal")
                        .WithMany()
                        .HasForeignKey("procurement_withdrawal_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Staffs", "Staff")
                        .WithMany()
                        .HasForeignKey("staff_id");

                    b.HasOne("Core.Entities.AssetUsageType", "AssetUsageType")
                        .WithMany()
                        .HasForeignKey("usage_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetUsageType");

                    b.Navigation("AssetWithdrawal");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("AssetItem", b =>
                {
                    b.HasOne("Core.Entities.AcquisitionMethod", "AcquisitionMethod")
                        .WithMany()
                        .HasForeignKey("acquisition_method_id");

                    b.HasOne("Core.Entities.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("department_id");

                    b.HasOne("Core.Entities.Fund_categories", "FundCategory")
                        .WithMany()
                        .HasForeignKey("fund_category_id");

                    b.Navigation("AcquisitionMethod");

                    b.Navigation("Department");

                    b.Navigation("FundCategory");
                });

            modelBuilder.Entity("AssetSubItem", b =>
                {
                    b.HasOne("AssetCategory", "asset_category")
                        .WithMany()
                        .HasForeignKey("asset_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetItem", "assetItem")
                        .WithMany()
                        .HasForeignKey("asset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialUnit", "materialUnit")
                        .WithMany()
                        .HasForeignKey("unit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assetItem");

                    b.Navigation("asset_category");

                    b.Navigation("materialUnit");
                });

            modelBuilder.Entity("Core.Entities.AssetRepair", b =>
                {
                    b.HasOne("Core.Entities.AssetWithdrawal", "assetWithdrawal")
                        .WithMany()
                        .HasForeignKey("procurement_withdrawal_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Staffs", "Staff")
                        .WithMany()
                        .HasForeignKey("staff_id");

                    b.Navigation("Staff");

                    b.Navigation("assetWithdrawal");
                });

            modelBuilder.Entity("Core.Entities.AssetWithdrawal", b =>
                {
                    b.HasOne("Core.Entities.Procurement_records", "ProcurementRecord")
                        .WithMany()
                        .HasForeignKey("procurement_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Staffs", "Staff")
                        .WithMany()
                        .HasForeignKey("staff_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcurementRecord");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Core.Entities.HireDetail", b =>
                {
                    b.HasOne("Core.Entities.Procurement_records", "procurement_record")
                        .WithMany()
                        .HasForeignKey("procurement_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialUnit", "unit")
                        .WithMany()
                        .HasForeignKey("unit_id");

                    b.Navigation("procurement_record");

                    b.Navigation("unit");
                });

            modelBuilder.Entity("Core.Entities.MaterialIssueDetail", b =>
                {
                    b.HasOne("Core.Entities.MaterialItem", "MaterialItem")
                        .WithMany()
                        .HasForeignKey("material_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Staffs", "Requester")
                        .WithMany()
                        .HasForeignKey("staff_id");

                    b.Navigation("MaterialItem");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Core.Entities.MaterialItem", b =>
                {
                    b.HasOne("MaterialUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("unit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Core.Entities.MaterialReceiveDetail", b =>
                {
                    b.HasOne("Core.Entities.MaterialItem", "MaterialItem")
                        .WithMany()
                        .HasForeignKey("material_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Procurement_records", "ProcurementRecord")
                        .WithMany()
                        .HasForeignKey("procurement_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialItem");

                    b.Navigation("ProcurementRecord");
                });

            modelBuilder.Entity("Core.Entities.MaterialStockCard", b =>
                {
                    b.HasOne("Core.Entities.MaterialIssueDetail", "IssueDetail")
                        .WithMany()
                        .HasForeignKey("issue_detail_id");

                    b.HasOne("Core.Entities.MaterialItem", "MaterialItem")
                        .WithMany()
                        .HasForeignKey("material_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.MaterialReceiveDetail", "ReceiveDetail")
                        .WithMany()
                        .HasForeignKey("receive_detail_id");

                    b.Navigation("IssueDetail");

                    b.Navigation("MaterialItem");

                    b.Navigation("ReceiveDetail");
                });

            modelBuilder.Entity("Core.Entities.MaterialWithdrawal", b =>
                {
                    b.HasOne("Core.Entities.Procurement_records", "ProcurementRecord")
                        .WithMany()
                        .HasForeignKey("procurement_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Staffs", "staffs")
                        .WithMany()
                        .HasForeignKey("staff_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcurementRecord");

                    b.Navigation("staffs");
                });

            modelBuilder.Entity("Core.Entities.Procurement_records", b =>
                {
                    b.HasOne("Core.Entities.Budget_sources", "budget_Sources")
                        .WithMany()
                        .HasForeignKey("budget_source_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Entities.Departments", "departments")
                        .WithMany()
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Entities.Expense_types", "expense_Types")
                        .WithMany()
                        .HasForeignKey("expense_type_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Entities.Fiscal_years", "fiscal_Years")
                        .WithMany()
                        .HasForeignKey("fiscal_year_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Entities.Fund_categories", "fund_Categories")
                        .WithMany()
                        .HasForeignKey("fund_category_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Entities.Operation_types", "operation_Types")
                        .WithMany()
                        .HasForeignKey("operation_type_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Entities.Projects", "projects")
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Staffs", "staffs")
                        .WithMany()
                        .HasForeignKey("staff_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Entities.Vendors", "vendors")
                        .WithMany()
                        .HasForeignKey("vendor_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("budget_Sources");

                    b.Navigation("departments");

                    b.Navigation("expense_Types");

                    b.Navigation("fiscal_Years");

                    b.Navigation("fund_Categories");

                    b.Navigation("operation_Types");

                    b.Navigation("projects");

                    b.Navigation("staffs");

                    b.Navigation("vendors");
                });

            modelBuilder.Entity("Core.Entities.Projects", b =>
                {
                    b.HasOne("Core.Entities.Fiscal_years", "fiscal_year")
                        .WithMany()
                        .HasForeignKey("fiscal_year_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Staffs", "staff")
                        .WithMany()
                        .HasForeignKey("staff_id");

                    b.Navigation("fiscal_year");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("Core.Entities.Staffs", b =>
                {
                    b.HasOne("Core.Entities.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Positions", "Positions")
                        .WithMany()
                        .HasForeignKey("position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Prefixes", "Prefixes")
                        .WithMany()
                        .HasForeignKey("prefix_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Positions");

                    b.Navigation("Prefixes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
